---
- name: UCS Infrastructure Pre-upgade playbook
  hosts: "{{ target }}"
  connection: local
  gather_facts: no
  vars:
    ucs_password: "notadmin"

# should run local since it defined as local
  tasks:
  - name: Make backup directory in /var/tmp
    file: path=/var/tmp/{{ target }} state=directory

  - name: Backup UCSM to Full backup
    shell: ./scripts/backupUcsManager.py -i "{{ inventory_hostname }}" -u admin -p "{{ ucs_password }}"  -t full-state -f /var/tmp/"{{ target }}"/full-state.xml

  - name: Backup UCSM to config-logical
    shell: ./scripts/backupUcsManager.py -i "{{ inventory_hostname }}" -u admin -p "{{ ucs_password }}"  -t config-logical -f /var/tmp/"{{ target }}"/config-logical-hostname.xml

  - name: Generate Tech-support file before upgrade. Can take a long time be patient
    shell: ./scripts/downloadTechSupportFile.py -i "{{ inventory_hostname }}" -u admin -p "{{ ucs_password }}"  -f /var/tmp/"{{ target }}"/tech_support.tar

  - name: Turn off Smart Call Home 
    shell: ./scripts/UCSM_callhome_on-off.py -u "{{ inventory_hostname }}" -p "{{ ucs_password }}"  -a off

#  - name: Make sure netboot is false for all nodes
#    shell: for i in $(cobbler system list); do echo $i; cobbler system edit --netboot-enabled=False --name=$i; done
