# Simple playbook to parallelize CIMC configs
# If we do hosts one by one it takes forever. Takes about 5-10 minutes per host
# We can safely run this in parallel
---
- name: Run CIMC script in para
#  hosts: "{{ target }}"
  hosts: all
  connection: local
  vars:
    - ucs_password: "notadmin"

  tasks:
 
# Script
    - name: Change passwords
      shell: ../BOM4_scripts/update_admin_pass.expect "{{ inventory_hostname }}" admin password123
      tags: pass

    - name: Create local accounts 
      shell: ../BOM4_scripts/UCSC_Add_Local_and_SNMP_User.py -H "{{ inventory_hostname }}" -u admin -p password -c ../BOM4_scripts/site-specific-config/eu-amsterdam-1_ucsc_local_and_snmp_users.yaml
      tags: accounts
 
    - name: Update CIMC settings
      shell: ./CIMC_generic_yaml_update.py -i "{{ inventory_hostname }}" -u admin -p "{{ ucs_password }}"  -c True -b ./C220M3-2Tor.yml 
      tags: cimc

